image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/java:corretto-17

stages:
  - test
  - build

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-cli:
  stage: build
  script:
    - ./gradlew cli:build
  tags:
    - arch:arm64

build-server:
  stage: build
  script:
    - ./gradlew server:build
  tags:
    - arch:arm64

test:
  stage: test
  script:
    - ./gradlew check
  tags:
    - arch:arm64

after_script:
  - echo "End CI"
