image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/java:corretto-17

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - juli1/STAT-81
  tags:
    - arch:arm64

test:
  stage: test
  script:
    - ./gradlew check
  tags:
    - arch:arm64

after_script:
  - echo "End CI"
