version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - yum install -y java-17-amazon-corretto-devel
    finally:
      - echo Preliminary tasks done
  pre_build:
    commands:
      - ./gradlew build
      - ./gradlew test
    finally:
      - echo pre-build done
  build:
    commands:
      - ./gradlew build
      - docker build --build-arg JAR_FILE=build/libs/\*.jar -t $IMAGE_NAME  .
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URL/$IMAGE_NAME:latest
      - echo "Pushing container"
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"$CONTAINER_NAME","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
    finally:
      - echo build done
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
    files: imagedefinitions.json
