package io.codiga.model;

public enum EntityChecked {
    ANY,
    ASSIGNMENT,
    CLASS_DEFINITION,
    FOR_LOOP,
    FUNCTION_CALL,
    FUNCTION_DEFINITION,
    FUNCTION_EXPRESSION,
    HTML_ELEMENT,
    IF_STATEMENT,
    INTERFACE,
    IMPORT_STATEMENT,
    VARIABLE_DECLARATION,
    TRY_BLOCK,
    TYPE,
    UNKNOWN,
}
