package io.codiga.model.ast.common;

public enum AstElementTypes {
    STRING("string"),
    LIST("list"),
    ARRAY("array"),
    OBJECT("object"),
    OBJECT_ELEMENT("object_element"),
    ASSIGNMENT("assignment"),
    ASSERT("assert"),
    VARIABLE_INDEX("variableindex"),
    ASSIGNMENTS("assignments"),
    CONTAINER("container"),
    RETURN("return"),
    TUPLE("tuple"),
    NONE("none"),
    NOT("not"),
    BREAK("break"),
    CONTINUE("continue"),
    SWITCH("switch"),
    SWITCH_CASE("switchcase"),
    SEQUENCE("sequence"),
    OPERATION("operation"),
    FUNCTION_CALL("functioncall"),
    FUNCTION_DEFINITION_PARAMETERS("functiondefinitionparameters"),
    FUNCTION_DEFINITION_PARAMETER("functiondefinitionparameter"),
    FUNCTION_EXCEPT_CLAUSE("exceptclause"),
    FUNCTION_FINALLY_CLAUSE("finallyclause"),
    FUNCTION_DEFINITION("functiondefinition"),
    FUNCTION_EXPRESSION("functionexpression"),
    CLASS_DEFINITION("classdefinition"),
    IMPORT_STATEMENT("importstatement"),
    IMPORTED_NAME("importedname"),
    COMPARISON("comparison"),
    EXPRESSION("expression"),
    ARGUMENT("argument"),
    DECORATOR("decorator"),
    DICTIONARY("dictionary"),
    DICTIONARY_ELEMENT("dictionaryelement"),
    IF_STATEMENT("ifstatement"),
    FOR_STATEMENT("forstatement"),
    ELIF_STATEMENT("elifstatement"),
    ELSE_STATEMENT("elsestatement"),
    FROM_STATEMENT("fromstatement"),
    TRY_STATEMENT("trystatement"),
    RAISE_STATEMENT("raisestatement"),
    CATCH_STATEMENT("catchstatement"),
    VARIABLE_DECLARATION("variabledeclaration"),
    MEMBER("member"),
    HTML_ELEMENT("htmlelement"),
    HTML_TAG("htmltag"),
    HTML_ATTRIBUTE("htmlattribute"),
    HTML_DATA("htmldata"),
    FROM_ELEMENT("fromelement"),
    PASS("pass"),
    IMPORT_PACKAGE("importpackage"),
    ARGUMENTS("arguments"),
    TYPE("type"),
    INTERFACE("interface"),
    INTERFACE_PROPERTY("interfaceproperty"),
    INTERFACE_INDEX_SIGNATURE("indexsignature"),
    TYPE_OPERATION("typeoperation"),
    WHILE_STATEMENT("whilestatement");

    public final String label;

    AstElementTypes(String l) {
        this.label = l;
    }
}
