name: Release new version

on:
  release:
    types: [created]

jobs:
  release-github:
    name: Build and publish on the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Set the version
        run: echo "package io.codiga.utils;\npublic final class Version {\n    public static final String CURRENT_VERSION = \"$GITHUB_SHA\";\n}" > > core/src/main/java/io/codiga/utils/Version.java
      - name: Build with Gradle
        run: ./gradlew cli:build
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./cli/build/distributions/cli-1.0-SNAPSHOT.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
